# Generated by Django 4.2 on 2026-03-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleta', '0012_cidade_remove_premioroleta_localidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletaconfig',
            name='limite_giros_por_membro',
            field=models.IntegerField(default=0, help_text='Número máximo de giros permitidos por pessoa. Use 0 para sem limite.'),
        ),
        migrations.AddField(
            model_name='roletaconfig',
            name='periodo_limite',
            field=models.CharField(choices=[('total', 'Total (para sempre)'), ('diario', 'Diário (por dia corrido)'), ('semanal', 'Semanal (últimos 7 dias)'), ('mensal', 'Mensal (mês atual)')], default='total', help_text='Janela de tempo usada para contar os giros de cada membro.', max_length=10),
        ),
    ]
