# Generated by Django 4.2 on 2026-03-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleta', '0013_limite_giros_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='premioroleta',
            name='mensagem_vitoria',
            field=models.TextField(blank=True, default='Você ganhou um prêmio!', help_text='Mensagem que aparecerá no alerta ao ganhar este prêmio.'),
        ),
    ]
