# Generated by Django 4.2 on 2026-03-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleta', '0014_premioroleta_mensagem_vitoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='regrapontuacao',
            name='visivel_na_roleta',
            field=models.BooleanField(default=True, help_text='Se marcado, esta missão aparecerá na lista da roleta para o usuário.'),
        ),
    ]
