# Generated by Django 4.2 on 2026-03-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleta', '0015_regrapontuacao_visivel_na_roleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='membroclube',
            name='codigo_indicacao',
            field=models.CharField(blank=True, help_text='Código único para link de indicação', max_length=10, null=True, unique=True),
        ),
    ]
