# Generated by Django 4.2 on 2026-03-20 16:10
# FAQ models moved to gestao app. This migration only keeps the non-FAQ alterations.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleta', '0016_membroclube_codigo_indicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membroclube',
            name='id_cliente_hubsoft',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='membroclube',
            name='validado',
            field=models.BooleanField(db_index=True, default=False, help_text='Se o membro já validou o OTP'),
        ),
        migrations.AlterField(
            model_name='participanteroleta',
            name='status',
            field=models.CharField(choices=[('reservado', 'Reservado'), ('ganhou', 'Ganhou'), ('inviavel_tec', 'Inviável Tecnicamente'), ('inviavel_cani', 'Inviável Cani')], db_index=True, default='reservado', max_length=50),
        ),
        migrations.AlterField(
            model_name='regrapontuacao',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
