# Generated by Django 4.2 on 2026-03-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleta', '0017_faq_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerClube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('imagem', models.ImageField(upload_to='banners/')),
                ('link', models.URLField(blank=True, help_text='URL ao clicar no banner (opcional)')),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='LandingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Clube Megalink', max_length=200)),
                ('subtitulo', models.CharField(default='Seu programa de fidelidade', max_length=300)),
                ('whatsapp_numero', models.CharField(blank=True, help_text='Numero com DDD (ex: 5586999999999)', max_length=20)),
                ('whatsapp_mensagem', models.CharField(default='Quero participar do Clube Megalink!', max_length=300)),
                ('texto_como_funciona', models.TextField(blank=True, help_text='Texto da secao Como Funciona (markdown)')),
                ('texto_rodape', models.CharField(blank=True, max_length=300)),
                ('cor_primaria', models.CharField(default='#000b4a', max_length=10)),
                ('cor_secundaria', models.CharField(default='#f59e0b', max_length=10)),
                ('logo', models.ImageField(blank=True, upload_to='landing/')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuracao Landing Page',
                'verbose_name_plural': 'Configuracao Landing Page',
            },
        ),
    ]
