# Generated by Django 4.2 on 2026-03-18 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roleta', '0016_membroclube_codigo_indicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_indicado', models.CharField(max_length=255)),
                ('telefone_indicado', models.CharField(max_length=20)),
                ('cpf_indicado', models.CharField(blank=True, max_length=14)),
                ('cidade_indicado', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('contato_feito', 'Contato Feito'), ('convertido', 'Convertido'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('pontos_creditados', models.BooleanField(default=False)),
                ('data_indicacao', models.DateTimeField(auto_now_add=True)),
                ('data_conversao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('membro_indicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicacao_recebida', to='roleta.membroclube')),
                ('membro_indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicacoes_feitas', to='roleta.membroclube')),
            ],
            options={
                'verbose_name': 'Indicação',
                'verbose_name_plural': 'Indicações',
                'ordering': ['-data_indicacao'],
                'unique_together': {('membro_indicador', 'telefone_indicado')},
            },
        ),
    ]
