from .helpers import *
from .dashboard import *
from .projetos import *
from .documentos import *
from .agentes import *
from .sala import *
from .api import *
from .automacoes import *
from .propostas_alertas import *
