# Generated by Django 4.2 on 2026-03-18 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roleta', '0016_membroclube_codigo_indicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupomDesconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: 20% off no Restaurante X', max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo_desconto', models.CharField(choices=[('percentual', 'Percentual (%)'), ('fixo', 'Valor Fixo (R$)')], max_length=15)),
                ('valor_desconto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modalidade', models.CharField(choices=[('gratuito', 'Gratuito'), ('pontos', 'Custo em Pontos'), ('nivel', 'Bônus de Nível')], default='gratuito', max_length=15)),
                ('custo_pontos', models.IntegerField(default=0, help_text='Usado quando modalidade = Pontos')),
                ('quantidade_total', models.IntegerField(default=0, help_text='0 = ilimitado')),
                ('quantidade_resgatada', models.IntegerField(default=0)),
                ('limite_por_membro', models.IntegerField(default=1)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cidades_permitidas', models.ManyToManyField(blank=True, related_name='cupons', to='roleta.cidade')),
                ('nivel_minimo', models.ForeignKey(blank=True, help_text='Usado quando modalidade = Nível', null=True, on_delete=django.db.models.deletion.SET_NULL, to='roleta.nivelclube')),
            ],
            options={
                'verbose_name': 'Cupom de Desconto',
                'verbose_name_plural': 'Cupons de Desconto',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='ResgateCupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.CharField(max_length=20, unique=True)),
                ('pontos_gastos', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('resgatado', 'Resgatado'), ('utilizado', 'Utilizado'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], default='resgatado', max_length=20)),
                ('data_resgate', models.DateTimeField(auto_now_add=True)),
                ('data_utilizacao', models.DateTimeField(blank=True, null=True)),
                ('cupom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resgates', to='parceiros.cupomdesconto')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resgates_cupom', to='roleta.membroclube')),
            ],
            options={
                'verbose_name': 'Resgate de Cupom',
                'verbose_name_plural': 'Resgates de Cupom',
                'ordering': ['-data_resgate'],
            },
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='parceiros/logos/')),
                ('descricao', models.TextField(blank=True)),
                ('contato_nome', models.CharField(blank=True, max_length=255)),
                ('contato_telefone', models.CharField(blank=True, max_length=20)),
                ('contato_email', models.EmailField(blank=True, max_length=254)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cidades', models.ManyToManyField(blank=True, related_name='parceiros', to='roleta.cidade')),
            ],
            options={
                'verbose_name': 'Parceiro',
                'verbose_name_plural': 'Parceiros',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='cupomdesconto',
            name='parceiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupons', to='parceiros.parceiro'),
        ),
    ]
