# Generated by Django 4.2 on 2026-03-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupomdesconto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='cupons/'),
        ),
    ]
