# Generated by Django 4.2 on 2026-03-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0002_cupomdesconto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='resgatecupom',
            name='valor_compra',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor total da compra no estabelecimento', max_digits=10, null=True),
        ),
    ]
