# Generated by Django 4.2 on 2026-03-18 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parceiros', '0003_resgatecupom_valor_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiro',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Usuário Django vinculado para acesso ao painel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parceiro', to=settings.AUTH_USER_MODEL),
        ),
    ]
