# Generated by Django 4.2 on 2026-03-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0004_parceiro_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupomdesconto',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, help_text='Motivo da rejeição (preenchido pelo admin)'),
        ),
        migrations.AddField(
            model_name='cupomdesconto',
            name='status_aprovacao',
            field=models.CharField(choices=[('aprovado', 'Aprovado'), ('pendente', 'Aguardando Aprovação'), ('rejeitado', 'Rejeitado')], default='aprovado', help_text='Cupons solicitados por parceiros ficam pendentes até aprovação', max_length=15),
        ),
    ]
