# Generated by Django 4.2 on 2026-03-22 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0005_cupomdesconto_motivo_rejeicao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaParceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icone', models.CharField(default='fas fa-tag', help_text='Classe FontAwesome', max_length=50)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de Parceiro',
                'verbose_name_plural': 'Categorias de Parceiros',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='cupomdesconto',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='cupomdesconto',
            name='data_fim',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cupomdesconto',
            name='status_aprovacao',
            field=models.CharField(choices=[('aprovado', 'Aprovado'), ('pendente', 'Aguardando Aprovação'), ('rejeitado', 'Rejeitado')], db_index=True, default='aprovado', help_text='Cupons solicitados por parceiros ficam pendentes até aprovação', max_length=15),
        ),
        migrations.AlterField(
            model_name='resgatecupom',
            name='data_resgate',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='resgatecupom',
            name='status',
            field=models.CharField(choices=[('resgatado', 'Resgatado'), ('utilizado', 'Utilizado'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], db_index=True, default='resgatado', max_length=20),
        ),
        migrations.AddField(
            model_name='parceiro',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parceiros', to='parceiros.categoriaparceiro'),
        ),
    ]
