# Generated by Django 4.2 on 2026-03-19 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roleta', '0016_membroclube_codigo_indicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloCarteirinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome interno do modelo (ex: Cartao Ouro)', max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('imagem_fundo', models.ImageField(help_text='Imagem de fundo do cartao (recomendado 600x380px)', upload_to='carteirinhas/modelos/')),
                ('cor_texto', models.CharField(default='#1e293b', help_text='Cor do texto sobre o fundo (hex)', max_length=7)),
                ('cor_texto_secundario', models.CharField(default='#64748b', help_text='Cor do texto secundario (hex)', max_length=7)),
                ('mostrar_nome', models.BooleanField(default=True)),
                ('mostrar_cpf', models.BooleanField(default=True)),
                ('mostrar_nivel', models.BooleanField(default=True)),
                ('mostrar_data_emissao', models.BooleanField(default=True)),
                ('mostrar_data_validade', models.BooleanField(default=False)),
                ('mostrar_qr_code', models.BooleanField(default=True, help_text='QR Code com link do perfil ou validacao')),
                ('mostrar_foto', models.BooleanField(default=False, help_text='Exibir foto do membro (requer upload)')),
                ('mostrar_pontos', models.BooleanField(default=False)),
                ('mostrar_cidade', models.BooleanField(default=False)),
                ('texto_rodape', models.CharField(blank=True, default='Clube Megalink', help_text='Texto no rodape do cartao', max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modelo de Carteirinha',
                'verbose_name_plural': 'Modelos de Carteirinha',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RegraAtribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nivel', 'Por Nível'), ('pontuacao_minima', 'Por Pontuação Mínima'), ('cidade', 'Por Cidade'), ('todos', 'Todos os Membros'), ('manual', 'Atribuição Manual')], max_length=20)),
                ('pontuacao_minima', models.IntegerField(default=0, help_text='Usado quando tipo = pontuacao_minima (XP minimo)')),
                ('cidade', models.CharField(blank=True, help_text='Usado quando tipo = cidade', max_length=100)),
                ('prioridade', models.IntegerField(default=0, help_text='Maior prioridade vence quando membro se encaixa em varias regras')),
                ('ativo', models.BooleanField(default=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='carteirinha.modelocarteirinha')),
                ('nivel', models.ForeignKey(blank=True, help_text='Usado quando tipo = nivel', null=True, on_delete=django.db.models.deletion.SET_NULL, to='roleta.nivelclube')),
            ],
            options={
                'verbose_name': 'Regra de Atribuição',
                'verbose_name_plural': 'Regras de Atribuição',
                'ordering': ['-prioridade'],
            },
        ),
        migrations.CreateModel(
            name='CarteirinhaMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='carteirinhas/fotos/')),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carteirinhas', to='roleta.membroclube')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissoes', to='carteirinha.modelocarteirinha')),
            ],
            options={
                'verbose_name': 'Carteirinha do Membro',
                'verbose_name_plural': 'Carteirinhas dos Membros',
                'ordering': ['-data_emissao'],
            },
        ),
    ]
