# Generated by Django 4.2 on 2026-03-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteirinha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelocarteirinha',
            name='cor_destaque',
            field=models.CharField(default='#fbbf24', help_text='Cor de destaque (nivel, badges)', max_length=7),
        ),
        migrations.AddField(
            model_name='modelocarteirinha',
            name='cor_fundo_primaria',
            field=models.CharField(default='#000b4a', help_text='Cor primaria do fundo (ou inicio do gradiente)', max_length=7),
        ),
        migrations.AddField(
            model_name='modelocarteirinha',
            name='cor_fundo_secundaria',
            field=models.CharField(default='#1a2d4a', help_text='Cor secundaria (fim do gradiente). Igual a primaria = cor solida', max_length=7),
        ),
        migrations.AddField(
            model_name='modelocarteirinha',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo exibido no cartao', null=True, upload_to='carteirinhas/logos/'),
        ),
        migrations.AddField(
            model_name='modelocarteirinha',
            name='texto_marca',
            field=models.CharField(default='Clube Megalink', help_text='Texto da marca (usado se nao tiver logo)', max_length=100),
        ),
        migrations.AddField(
            model_name='modelocarteirinha',
            name='tipo_fundo',
            field=models.CharField(choices=[('cor', 'Cores / Gradiente'), ('imagem', 'Imagem de Fundo')], default='cor', max_length=10),
        ),
        migrations.AlterField(
            model_name='modelocarteirinha',
            name='cor_texto',
            field=models.CharField(default='#ffffff', help_text='Cor do texto principal', max_length=7),
        ),
        migrations.AlterField(
            model_name='modelocarteirinha',
            name='cor_texto_secundario',
            field=models.CharField(default='#94a3b8', help_text='Cor do texto secundario (labels)', max_length=7),
        ),
        migrations.AlterField(
            model_name='modelocarteirinha',
            name='imagem_fundo',
            field=models.ImageField(blank=True, help_text='Imagem de fundo (600x380px). Usado quando tipo_fundo = imagem', null=True, upload_to='carteirinhas/modelos/'),
        ),
        migrations.AlterField(
            model_name='modelocarteirinha',
            name='mostrar_foto',
            field=models.BooleanField(default=False, help_text='Exibir foto do membro'),
        ),
        migrations.AlterField(
            model_name='modelocarteirinha',
            name='mostrar_qr_code',
            field=models.BooleanField(default=True, help_text='QR Code com link de validacao'),
        ),
        migrations.AlterField(
            model_name='modelocarteirinha',
            name='texto_rodape',
            field=models.CharField(blank=True, default='um clube filiado', help_text='Texto pequeno no rodape', max_length=255),
        ),
    ]
