# Generated by Django 4.2 on 2026-03-19 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('agentes', models.CharField(help_text='IDs dos agentes separados por virgula (ex: cto,cpo,cfo)', max_length=200)),
                ('ativa', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reunião',
                'verbose_name_plural': 'Reuniões',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='MensagemReuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ceo', 'CEO'), ('agente', 'Agente'), ('moderador', 'Moderador')], max_length=10)),
                ('agente_id', models.CharField(blank=True, help_text='ID do agente (se tipo=agente)', max_length=20)),
                ('agente_nome', models.CharField(blank=True, max_length=100)),
                ('conteudo', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='gestao.reuniao')),
            ],
            options={
                'ordering': ['data_criacao'],
            },
        ),
    ]
