# Generated by Django 4.2 on 2026-03-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_reuniao_mensagemreuniao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('agente', models.CharField(choices=[('cto', 'CTO'), ('cpo', 'CPO'), ('cfo', 'CFO'), ('cmo', 'CMO'), ('pmm', 'PMM'), ('b2b', 'Comercial B2B'), ('cs', 'Customer Success'), ('ceo', 'CEO')], max_length=10)),
                ('conteudo', models.TextField(help_text='Conteudo em markdown')),
                ('resumo', models.TextField(blank=True, help_text='Resumo curto para contexto dos agentes')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('agente', models.CharField(choices=[('cto', 'CTO'), ('cpo', 'CPO'), ('cfo', 'CFO'), ('cmo', 'CMO'), ('pmm', 'PMM'), ('b2b', 'Comercial B2B'), ('cs', 'Customer Success'), ('ceo', 'CEO')], max_length=10)),
                ('resumo', models.TextField(blank=True, help_text='Resumo das decisoes tomadas')),
                ('conteudo', models.TextField(help_text='Transcricao completa em markdown')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sessão',
                'verbose_name_plural': 'Sessões',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
