# Generated by Django 4.2 on 2026-03-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_agente_alter_entrega_agente_alter_sessao_agente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('slug', models.SlugField(help_text='Identificador unico (ex: estrategia, regras-negocio)', max_length=100, unique=True)),
                ('categoria', models.CharField(choices=[('estrategia', 'Estratégia'), ('regras', 'Regras de Negócio'), ('roadmap', 'Roadmap'), ('decisoes', 'Decisões'), ('contexto', 'Base de Conhecimento'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('conteudo', models.TextField(help_text='Conteudo em markdown')),
                ('descricao', models.CharField(blank=True, help_text='Descricao curta do documento', max_length=300)),
                ('visivel_agentes', models.BooleanField(default=True, help_text='Se True, agentes IA recebem este doc como contexto')),
                ('ordem', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['ordem', 'categoria', 'titulo'],
            },
        ),
        migrations.AlterField(
            model_name='agente',
            name='cor',
            field=models.CharField(default='#3b82f6', help_text='Cor hex', max_length=10),
        ),
        migrations.AlterField(
            model_name='agente',
            name='descricao',
            field=models.CharField(help_text='Descricao curta (ex: Tecnologia e Arquitetura)', max_length=200),
        ),
        migrations.AlterField(
            model_name='agente',
            name='icone',
            field=models.CharField(default='fas fa-robot', help_text='Classe FontAwesome', max_length=50),
        ),
        migrations.AlterField(
            model_name='agente',
            name='modelo',
            field=models.CharField(default='gpt-4o-mini', help_text='Modelo da OpenAI', max_length=50),
        ),
        migrations.AlterField(
            model_name='agente',
            name='nome',
            field=models.CharField(help_text='Nome de exibicao (ex: CTO, Comercial B2B)', max_length=100),
        ),
        migrations.AlterField(
            model_name='agente',
            name='prompt',
            field=models.TextField(help_text='System prompt completo do agente (markdown)'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='slug',
            field=models.SlugField(help_text='ID unico (ex: cto, cmo, b2b)', max_length=20, unique=True),
        ),
    ]
