# Generated by Django 4.2 on 2026-03-20 00:51
# Modified: add data migration to move Entrega -> Documento before deleting

from django.db import migrations, models
import django.db.models.deletion
import uuid


def migrar_entregas_para_documentos(apps, schema_editor):
    """Copia registros de Entrega para Documento com categoria='entrega'."""
    Entrega = apps.get_model('gestao', 'Entrega')
    Documento = apps.get_model('gestao', 'Documento')

    for e in Entrega.objects.all():
        Documento.objects.create(
            titulo=e.titulo,
            slug=f"entrega-{uuid.uuid4().hex[:8]}",
            categoria='entrega',
            agente_id=e.agente_id,
            conteudo=e.conteudo,
            resumo=e.resumo,
            descricao=e.resumo[:300] if e.resumo else '',
            visivel_agentes=True,
            ordem=50,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_documento_alter_agente_cor_alter_agente_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='agente',
            field=models.ForeignKey(blank=True, help_text='Agente autor (para entregas)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='gestao.agente'),
        ),
        migrations.AddField(
            model_name='documento',
            name='resumo',
            field=models.TextField(blank=True, help_text='Resumo curto para contexto dos agentes'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='categoria',
            field=models.CharField(choices=[('estrategia', 'Estratégia'), ('regras', 'Regras de Negócio'), ('roadmap', 'Roadmap'), ('decisoes', 'Decisões'), ('entrega', 'Entrega de Agente'), ('contexto', 'Base de Conhecimento'), ('outro', 'Outro')], default='outro', max_length=20),
        ),
        # Data migration: copiar Entrega -> Documento ANTES de deletar
        migrations.RunPython(migrar_entregas_para_documentos, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='Entrega',
        ),
    ]
