# Generated by Django 4.2 on 2026-03-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_alter_documento_categoria_delete_sessao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='ID unico (ex: salvar_documento, calculadora_roi)', unique=True)),
                ('nome', models.CharField(help_text='Nome de exibicao', max_length=100)),
                ('descricao', models.CharField(help_text='Descricao curta do que a tool faz', max_length=300)),
                ('tipo', models.CharField(choices=[('executavel', 'Executável'), ('conhecimento', 'Conhecimento')], default='conhecimento', max_length=20)),
                ('prompt', models.TextField(help_text='Instrucoes/prompt da tool (como o agente deve usar)')),
                ('exemplo', models.TextField(blank=True, help_text='Exemplo de uso ou formato de saida')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tool de Agente',
                'verbose_name_plural': 'Tools de Agentes',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
