# Generated by Django 4.2 on 2026-03-20 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_mensagemchat'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_slug', models.CharField(help_text='Slug da tool no momento da execucao', max_length=50)),
                ('resultado', models.TextField(help_text='Resultado da execucao')),
                ('sucesso', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_tools', to='gestao.agente')),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='gestao.toolagente')),
            ],
            options={
                'verbose_name': 'Log de Tool',
                'verbose_name_plural': 'Logs de Tools',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
