# Generated by Django 4.2 on 2026-03-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_logtool'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='contexto_agentes',
            field=models.TextField(blank=True, help_text='Informacoes extras que os agentes IA devem saber sobre este projeto'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='criterios_sucesso',
            field=models.TextField(blank=True, help_text='Como sabemos que deu certo? KPIs e metas concretas'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='objetivo',
            field=models.TextField(blank=True, help_text='O que este projeto deve alcancar? Qual problema resolve?'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='orcamento',
            field=models.TextField(blank=True, help_text='Budget disponivel, custos previstos'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='premissas',
            field=models.TextField(blank=True, help_text='Premissas assumidas (ex: parceiro X vai aceitar, budget aprovado)'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='prioridade',
            field=models.CharField(choices=[('critica', 'Crítica'), ('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='projeto',
            name='publico_alvo',
            field=models.TextField(blank=True, help_text='Para quem? (ex: membros Floriano, parceiros restaurantes)'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='riscos',
            field=models.TextField(blank=True, help_text='O que pode dar errado? Dependencias externas?'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='stakeholders',
            field=models.TextField(blank=True, help_text='Quem esta envolvido e qual o papel de cada um (1 por linha: Nome - Papel)'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('planejamento', 'Planejamento'), ('em_andamento', 'Em Andamento'), ('pausado', 'Pausado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejamento', max_length=20),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descricao geral do projeto'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='responsavel',
            field=models.CharField(blank=True, help_text='Dono do projeto (ex: CEO, PMM)', max_length=100),
        ),
    ]
