# Generated by Django 4.2 on 2026-03-20 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0011_projeto_contexto_agentes_projeto_criterios_sucesso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('icone', models.CharField(default='fas fa-bolt', max_length=50)),
                ('cor', models.CharField(default='#f59e0b', max_length=10)),
                ('comando', models.CharField(blank=True, help_text='Management command (ex: gerar_faq)', max_length=200)),
                ('intervalo_horas', models.IntegerField(default=24, help_text='Intervalo entre execuções em horas')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('pausado', 'Pausado'), ('erro', 'Com Erro')], db_index=True, default='ativo', max_length=20)),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True)),
                ('proximo_execucao', models.DateTimeField(blank=True, null=True)),
                ('ultimo_resultado', models.TextField(blank=True)),
                ('total_execucoes', models.IntegerField(default=0)),
                ('total_erros', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Automação',
                'verbose_name_plural': 'Automações',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FAQCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icone', models.CharField(default='fas fa-question-circle', max_length=50)),
                ('cor', models.CharField(default='#3b82f6', max_length=10)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Categoria FAQ',
                'verbose_name_plural': 'Categorias FAQ',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='agente',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='categoria',
            field=models.CharField(choices=[('estrategia', 'Estratégia'), ('regras', 'Regras de Negócio'), ('roadmap', 'Roadmap'), ('decisoes', 'Decisões'), ('entrega', 'Entrega de Agente'), ('sessao', 'Sessão com Agente'), ('contexto', 'Base de Conhecimento'), ('outro', 'Outro')], db_index=True, default='outro', max_length=20),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('planejamento', 'Planejamento'), ('em_andamento', 'Em Andamento'), ('pausado', 'Pausado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], db_index=True, default='planejamento', max_length=20),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='ativa',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('bloqueada', 'Bloqueada')], db_index=True, default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='toolagente',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.CreateModel(
            name='LogAutomacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucesso', models.BooleanField(default=True)),
                ('resultado', models.TextField(blank=True)),
                ('itens_processados', models.IntegerField(default=0)),
                ('duracao_ms', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('automacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='gestao.automacao')),
            ],
            options={
                'verbose_name': 'Log de Automação',
                'verbose_name_plural': 'Logs de Automações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=500)),
                ('resposta', models.TextField()),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('gerado_por_ia', models.BooleanField(default=False)),
                ('hash_dados_fonte', models.CharField(blank=True, max_length=64)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='gestao.faqcategoria')),
            ],
            options={
                'verbose_name': 'Item FAQ',
                'verbose_name_plural': 'Itens FAQ',
                'ordering': ['categoria__ordem', 'ordem'],
            },
        ),
        migrations.AddField(
            model_name='automacao',
            name='agente',
            field=models.ForeignKey(blank=True, help_text='Agente IA responsável', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automacoes', to='gestao.agente'),
        ),
    ]
