# Generated by Django 4.2 on 2026-03-21 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0013_automacao_refactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('health', 'Saúde do Sistema'), ('estoque', 'Estoque Baixo'), ('churn', 'Risco de Churn'), ('metrica', 'Métrica Anormal'), ('erro', 'Erro de Execução'), ('outro', 'Outro')], db_index=True, default='outro', max_length=20)),
                ('severidade', models.CharField(choices=[('info', 'Informação'), ('aviso', 'Aviso'), ('critico', 'Crítico')], db_index=True, default='info', max_length=10)),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.TextField(blank=True)),
                ('dados_json', models.JSONField(blank=True, default=dict, help_text='Dados extras estruturados (métricas, IDs afetados, etc.)')),
                ('lido', models.BooleanField(db_index=True, default=False)),
                ('resolvido', models.BooleanField(db_index=True, default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(blank=True, help_text='Agente que gerou o alerta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='gestao.agente')),
                ('tool', models.ForeignKey(blank=True, help_text='Tool que gerou o alerta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='gestao.toolagente')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.TextField(help_text='O que será feito e por quê')),
                ('prioridade', models.CharField(choices=[('critica', 'Crítica'), ('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='media', max_length=10)),
                ('dados_execucao', models.JSONField(blank=True, default=dict, help_text='Parâmetros para execução da tool (ex: bloco de ação)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('executada', 'Executada'), ('erro', 'Erro na Execução')], db_index=True, default='pendente', max_length=10)),
                ('motivo_rejeicao', models.TextField(blank=True)),
                ('resultado_execucao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_decisao', models.DateTimeField(blank=True, null=True)),
                ('data_execucao', models.DateTimeField(blank=True, null=True)),
                ('agente', models.ForeignKey(help_text='Agente que propôs a ação', on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='gestao.agente')),
                ('alerta', models.ForeignKey(blank=True, help_text='Alerta que originou esta proposta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas', to='gestao.alerta')),
                ('reuniao', models.ForeignKey(blank=True, help_text='Reunião onde foi discutida', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas', to='gestao.reuniao')),
                ('tool', models.ForeignKey(blank=True, help_text='Tool que será executada após aprovação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas', to='gestao.toolagente')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
