# Generated by Django 4.2 on 2026-03-21 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0014_proposta_alerta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automacao',
            options={'ordering': ['tool__nome'], 'verbose_name': 'Automacao', 'verbose_name_plural': 'Automacoes'},
        ),
        migrations.AlterUniqueTogether(
            name='automacao',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='automacao',
            name='encaminhar_para',
            field=models.ForeignKey(blank=True, help_text='Agente que recebe o resultado para analisar (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automacoes_encaminhadas', to='gestao.agente'),
        ),
        migrations.AlterField(
            model_name='automacao',
            name='intervalo_horas',
            field=models.IntegerField(default=24, help_text='Intervalo entre execucoes em horas'),
        ),
        migrations.AlterField(
            model_name='automacao',
            name='tool',
            field=models.ForeignKey(help_text='Tool que sera executada', on_delete=django.db.models.deletion.CASCADE, related_name='automacoes', to='gestao.toolagente'),
        ),
        migrations.RemoveField(
            model_name='automacao',
            name='agente',
        ),
    ]
