# Generated by Django 4.2 on 2026-03-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0015_automacao_encaminhar_para'),
    ]

    operations = [
        migrations.AddField(
            model_name='automacao',
            name='ultima_analise',
            field=models.TextField(blank=True, help_text='Ultima analise do agente sobre o resultado'),
        ),
    ]
