# Generated by Django 4.2 on 2026-03-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0016_automacao_ultima_analise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='time',
            field=models.CharField(choices=[('executivo', 'C-Level'), ('marketing', 'Marketing'), ('sucesso', 'Customer Success'), ('parcerias', 'Parcerias'), ('tech', 'Produto & Tech')], default='executivo', max_length=20),
        ),
    ]
