# Generated by Django 4.2 on 2026-03-21 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0017_agente_time_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automacao',
            options={'ordering': ['modo', 'agente__nome', 'tool__nome'], 'verbose_name': 'Automacao', 'verbose_name_plural': 'Automacoes'},
        ),
        migrations.AddField(
            model_name='automacao',
            name='agente',
            field=models.ForeignKey(blank=True, help_text='Agente que sera acordado (modo=agente)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automacoes_agente', to='gestao.agente'),
        ),
        migrations.AddField(
            model_name='automacao',
            name='modo',
            field=models.CharField(choices=[('tool', 'Executar Tool'), ('agente', 'Acordar Agente')], default='tool', help_text='tool: executa tool direto. agente: acorda agente para trabalhar sozinho.', max_length=10),
        ),
        migrations.AlterField(
            model_name='automacao',
            name='encaminhar_para',
            field=models.ForeignKey(blank=True, help_text='Agente que recebe o resultado para analisar (modo=tool, opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automacoes_encaminhadas', to='gestao.agente'),
        ),
        migrations.AlterField(
            model_name='automacao',
            name='tool',
            field=models.ForeignKey(blank=True, help_text='Tool que sera executada (modo=tool)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automacoes', to='gestao.toolagente'),
        ),
    ]
