# Generated by Django 4.2 on 2026-03-22 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0018_automacao_modo_agente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='categoria',
            field=models.CharField(choices=[('estrategia', 'Estratégia'), ('regras', 'Regras de Negócio'), ('roadmap', 'Roadmap'), ('decisoes', 'Decisões'), ('entrega', 'Entrega de Agente'), ('sessao', 'Sessão com Agente'), ('contexto', 'Base de Conhecimento'), ('relatorio', 'Relatório'), ('outro', 'Outro')], db_index=True, default='outro', max_length=20),
        ),
        migrations.CreateModel(
            name='PastaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icone', models.CharField(blank=True, default='fas fa-folder', max_length=50)),
                ('cor', models.CharField(blank=True, default='#3b82f6', max_length=20)),
                ('ordem', models.IntegerField(default=0)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subpastas', to='gestao.pastadocumento')),
            ],
            options={
                'verbose_name_plural': 'Pastas de Documentos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='pasta',
            field=models.ForeignKey(blank=True, help_text='Pasta de organizacao (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='gestao.pastadocumento'),
        ),
    ]
