# Generated by Django 4.2 on 2026-03-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0019_pasta_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtool',
            name='tempo_ms',
            field=models.IntegerField(blank=True, help_text='Tempo de execucao em ms', null=True),
        ),
    ]
