# Generated by Django 4.2 on 2026-03-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0020_logtool_tempo_ms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='categoria',
            field=models.CharField(choices=[('estrategia', 'Estratégia'), ('regras', 'Regras de Negócio'), ('roadmap', 'Roadmap'), ('decisoes', 'Decisões'), ('entrega', 'Entrega de Agente'), ('sessao', 'Sessão com Agente'), ('contexto', 'Base de Conhecimento'), ('relatorio', 'Relatório'), ('email', 'Template de E-mail'), ('outro', 'Outro')], db_index=True, default='outro', max_length=20),
        ),
    ]
