# Generated by Django 4.2 on 2026-03-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0021_documento_categoria_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='contexto',
            field=models.TextField(blank=True, help_text='Inputs, referencias, publico-alvo, tom, restricoes'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='criterios_aceite',
            field=models.TextField(blank=True, help_text='Como saber que a tarefa esta concluida corretamente'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='entregavel',
            field=models.CharField(blank=True, help_text='O que deve ser produzido (ex: documento de e-mail)', max_length=300),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='objetivo',
            field=models.TextField(blank=True, help_text='O que esta tarefa deve alcancar'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='passos',
            field=models.TextField(blank=True, help_text='Passo-a-passo numerado que o agente deve seguir'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='pasta_destino',
            field=models.ForeignKey(blank=True, help_text='Pasta onde o entregavel deve ser salvo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_destino', to='gestao.pastadocumento'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='processo',
            field=models.ForeignKey(blank=True, help_text='Documento de processo/receita que originou esta tarefa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_processo', to='gestao.documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='categoria',
            field=models.CharField(choices=[('estrategia', 'Estratégia'), ('regras', 'Regras de Negócio'), ('roadmap', 'Roadmap'), ('decisoes', 'Decisões'), ('entrega', 'Entrega de Agente'), ('sessao', 'Sessão com Agente'), ('contexto', 'Base de Conhecimento'), ('relatorio', 'Relatório'), ('email', 'Template de E-mail'), ('processo', 'Processo'), ('outro', 'Outro')], db_index=True, default='outro', max_length=20),
        ),
    ]
