# Generated by Django 4.2 on 2026-03-22 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0022_tarefa_campos_estruturados'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='prompt_autonomo',
            field=models.TextField(blank=True, default='', help_text='System prompt para modo autonomo/automacao (se vazio, usa o prompt principal)'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='criado_por_agente',
            field=models.ForeignKey(blank=True, help_text='Agente que criou/delegou esta tarefa (None = criada por humano)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_criadas', to='gestao.agente'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='nivel_delegacao',
            field=models.IntegerField(default=0, help_text='0=humano, 1=delegada por agente, 2=sub-delegada. Max 2.'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='prompt',
            field=models.TextField(help_text='System prompt para chat interativo (markdown)'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('bloqueada', 'Bloqueada')], db_index=True, default='pendente', max_length=20),
        ),
    ]
