# Generated by Django 4.2 on 2026-03-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0023_agente_prompt_autonomo_tarefa_criado_por_agente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='log_execucao',
            field=models.TextField(blank=True, default='', help_text='Historico de execucao da tarefa (preenchido automaticamente)'),
        ),
    ]
