# Generated by Django 4.2 on 2026-03-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0024_tarefa_log_execucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='arquivo',
            field=models.ImageField(blank=True, help_text='Imagem gerada por IA', null=True, upload_to='geradas/'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='categoria',
            field=models.CharField(choices=[('estrategia', 'Estratégia'), ('regras', 'Regras de Negócio'), ('roadmap', 'Roadmap'), ('decisoes', 'Decisões'), ('entrega', 'Entrega de Agente'), ('sessao', 'Sessão com Agente'), ('contexto', 'Base de Conhecimento'), ('relatorio', 'Relatório'), ('email', 'Template de E-mail'), ('processo', 'Processo'), ('imagem', 'Imagem Gerada'), ('outro', 'Outro')], db_index=True, default='outro', max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='conteudo',
            field=models.TextField(blank=True, help_text='Conteudo em markdown'),
        ),
    ]
